#remote_theme: pages-themes/slate@v0.2.0
#remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0
remote_theme: poole/hyde
title: andreaminio.github.io
description: Andrea's little space
author: andrea.minio

github:
  is_project_page: false

footer_content: ""

plugins:
  - jekyll-remote-theme
