#remote_theme: pages-themes/slate@v0.2.0
#remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0
#remote_theme: sharu725/online-cv
remote_theme: amitmerchant1990/reverie
#remote_theme: codeasashu/hcz-jekyll-blog
#remote_theme: MrGreensWorkshop/MrGreen-JekyllTheme

title: andreaminio.github.io
description: Andrea's little space
author: andrea.minio

github:
  is_project_page: false

footer_content: ""

plugins:
  - jekyll-remote-theme

#darkmode: true
